language: go
go: [1.5.2]
install:
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.30.zip
  - unzip -q go_appengine_sdk_linux_amd64-1.9.30.zip
script:
  - ./go_appengine/goapp test ./src/...
  - ./go_appengine/goapp build ./src/...
