application: facts-exposed
version: 1
runtime: go
api_version: go1
inbound_services: [warmup]

handlers:
  - url: /([^/]*\.html)$
    static_files: static/\1
    upload: static/.*\.html$
  - url: /static
    static_dir: static
  - url: /
    static_files: static/index.html
    upload: static/index.html
  - url: /.*
    script: _go_app
